Fix debian package installation instructions
wagoodman/dive pull request #479
Opened 2023-09-27 14:12 UTC by micah

The correct command to run is `dpkg -i` on a debian package file. The instructions said to use `apt install` which does not work to install from a file.

2024-01-13 11:24 UTC, ReneNyffenegger commented
I was able to install dive with exactly the instructions given in the README.md for Debian.

2024-02-03 10:38 UTC, Okeanos requested changes

2024-02-03 10:38 UTC, Okeanos commented on README.md
> +sudo dokg -i ./dive_${DIVE_VERSION}_linux_amd64.deb
```suggestion
sudo dpkg -i ./dive_${DIVE_VERSION}_linux_amd64.deb
```

Assuming `apt install` doesn't work as expected, there's still a typo in here that needs to be fixed.

2024-02-16 13:22 UTC, edwardbaidoo commented
I believe `apt install` was used here since it would proceed to install missing dependencies(If any) as it installs the package.

2024-02-16 13:23 UTC, edwardbaidoo commented
> The correct command to run is `dpkg -i` on a debian package file. The instructions said to use `apt install` which does not work to install from a file.


I believe `apt install` was used here since it would proceed to install missing dependencies(If any) as it installs the package.

2024-11-06 14:22 UTC, joschi commented
The instructions in the README are indeed working:

```
❯ docker run -it --rm --name ubuntu-dive ubuntu:24.10
root@4f21e03e2da0:/# apt update -q
[...]
All packages are up to date.

root@4f21e03e2da0:/# apt install -q -y curl apt-utils
[...]

root@4f21e03e2da0:/# export DIVE_VERSION=$(curl -sL "https://api.github.com/repos/wagoodman/dive/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
root@4f21e03e2da0:/# echo $DIVE_VERSION
0.12.0

root@4f21e03e2da0:/# curl -OL https://github.com/wagoodman/dive/releases/download/v${DIVE_VERSION}/dive_${DIVE_VERSION}_linux_amd64.deb
[...]

root@4f21e03e2da0:/# apt install ./dive_${DIVE_VERSION}_linux_amd64.deb
[...]
Preparing to unpack /dive_0.12.0_linux_amd64.deb ...
Unpacking dive (0.12.0) ...
Setting up dive (0.12.0) ...

root@4f21e03e2da0:/# dive --version
dive 0.12.0
```

2024-11-06 16:14 UTC, micah commented
Apologies, I didn't realize that `apt install` will work on .deb files. 

/close

2024-11-06 16:14 UTC, closed without merging